stages:
  check:
    cmd: uv run src/check.py data/raw
    deps:
    - src/check.py
    - data/raw
    params:
    - mlflow.tracking_uri
    - mlflow.experiment_name
    - prepare.dataset
    outs:
    - logs/check.log
    - check/
  prepare:
    cmd: uv run src/prepare.py data/raw
    deps:
    - data/raw
    params:
    - prepare.dataset
    - prepare.adjustment.attempted
    - prepare.adjustment.tool_separate
    - prepare.test_size
    - prepare.sampling
    - prepare.sampling_params.method
    - prepare.sampling_params.params
    outs:
    - data/prepared/
    - logs/prepare.log
  train:
    cmd: uv run src/train.py --no-offline
    deps:
    - src/classifier
    - src/train.py
    - data/prepared/train
    params:
    - train.classifier.model
    - train.classifier.params.max_depth
    - mlflow.tracking_uri
    - mlflow.experiment_name
    outs:
    - data/models
    - logs/train.log
  evaluate:
    cmd: uv run src/evaluate.py --no-offline
    deps:
    - src/classifier
    - src/evaluate.py
    - data/prepared/test
    params:
    - mlflow.tracking_uri
    - mlflow.experiment_name
    outs:
    - evaluate
    - logs/evaluate.log
metrics:
- evaluate/metrics.json
plots:
- evaluate/plots/images
- evaluate/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
