mlflow:
  tracking_uri: http://127.0.0.1:5000
  experiment_name: test_air

prepare:
  dataset: CICIDS2017_improved
  adjustment:
    combine_web_attack: true
    attempted: false
    tool_separate: false
  test_size: 0.3
  sampling: None
  sampling_params:
    method: None
    params:
      sampling_strategy: not minority
      min_samples: 100
      neighbors: 3
      seed: 42

train:
  classifier: 
    model: ImprovedC45
    params:
      max_depth: 10
